### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stefbowerman** [stefbowerman/flatground-entertainment#3]
- [x] Mobile Menu
- [ ] Home Page Sections
  - [x] Video (YouTube, Vimeo, File URL)
  - [ ] Endless Blog Mosaic (single hard coded section)
  - What else goes on here?
- [x] Template + App audit to ensure feature parity
  - [x] 404
  - [x] Article
  - [x] Blog
  - [x] Cart
    - Has bold theme hooks - needed?
  - [x] Collection
  - [x] Index
  - [x] list-collections
  - [x] page.contact
  - [x] page.radio
  - [x] password
  - [x] product
  - [x] Search
- [x] Do we want the mini logo on the header for mobile?
- [x] Account pages
- [x] Add sorting and filtering on the PLP
- [x] Add a way to logout on account pages
- [x] Style checkout
- [x] Frontend filtering for sizes and colors.  We can use the Outerknown solution for sizes at least.  Leave this for discussion.  
- [x] What to do about size guide?
- [ ] Frontend App Integrations
  - [x] Back in Stock - Need to do this after redesign goes live.
  - [x] Product Discount - Keep it until post launch.  Figure out how to do with Shopify scripts.
  - [x] Product Options - Leave until post launch.  Possibly use Shopify scripts
  - [ ] Product Upsell - Works well, needs styling. Ned to contact bold about integration with AJAX Cart.
  - [x] Sales Motivator - Using pencil banner instead.
  - [ ] Multi Currency - Can we remove?
